// Generated product catalogue — edit here to update product detail pages.
window.UDARA_PRODUCTS = [
  {
    "id": "ying-and-yang",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Ying &amp; Yang",
    "name": "Ying &amp; Yang",
    "meta": "Set of 2 · 256 &amp; 384 Hz",
    "desc": "The Perfect Fifth — the most consonant interval in music. Played left and right, it synchronises the two hemispheres of the mind.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-front.png",
    "webp": "assets/products/fork-front.webp",
    "alt": "Ying &amp; Yang",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "heart-om",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Heart Om",
    "name": "Heart Om",
    "meta": "Set of 2 · 136.10 &amp; 355.55 Hz",
    "desc": "A meeting of two hearts — physical and spiritual. Harmonises emotion and releases deep blocks, bridging body and soul.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-hero.png",
    "webp": "assets/products/fork-hero.webp",
    "alt": "Heart Om",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "brainwave",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Brainwave",
    "name": "Brainwave",
    "meta": "Set of 5 · Binaural Beats",
    "desc": "A 256 Hz carrier paired with Delta, Theta, Alpha and Beta forks. The beat between them entrains the mind into the chosen state in minutes.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-detail.png",
    "webp": "assets/products/fork-detail.webp",
    "alt": "Brainwave",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "solfeggio",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Solfeggio",
    "name": "Solfeggio",
    "meta": "Set of 9 · Sacred Tones",
    "desc": "The ancient six-tone scale once sung in sacred chants — 396 to 852 Hz, with extended 963, 285 &amp; 147 Hz. Each tone a sonic prayer for deep healing.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-poster.jpg",
    "webp": "assets/products/fork-poster.webp",
    "alt": "Solfeggio",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "planetary",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Planetary",
    "name": "Planetary",
    "meta": "Set of 11 · The Cosmic Octave",
    "desc": "Hans Cousto’s masterwork made audible — Sun, Moon, Earth and the planets, each orbit octaved up into a tone you can feel.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-front.png",
    "webp": "assets/products/fork-front.webp",
    "alt": "Planetary",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "chakra",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Chakra",
    "name": "Chakra",
    "meta": "Set of 7 or 8 · Coloured",
    "desc": "Each energy centre matched to a planetary frequency and colour. Played in sequence, a sonic massage that clears and realigns body and spirit.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-hero.png",
    "webp": "assets/products/fork-hero.webp",
    "alt": "Chakra",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "light-weight-forks",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Light Weight",
    "name": "Light Weight Forks",
    "meta": "Aluminium · Earth · Sun · Cosmic Light",
    "desc": "Made from light aluminium and easy to handle — bright, clear tones, ideal for working in the aura and cleansing a space.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-detail.png",
    "webp": "assets/products/fork-detail.webp",
    "alt": "Light Weight",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "jumbo-forks",
    "category": "forks",
    "categoryName": "Tuning Forks",
    "label": "Jumbo",
    "name": "Jumbo Forks",
    "meta": "Weighted · 32–263 Hz · 3 sizes",
    "desc": "The giants of the family — felt more than heard. Adjustable weights and deep, palpable vibration travelling through the body by bone conduction. Hard case, mallet &amp; key included.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/fork-poster.jpg",
    "webp": "assets/products/fork-poster.webp",
    "alt": "Jumbo",
    "howto": "Tap the fork on a puck or your knee. Bring it close to each ear to quiet the mind, or rest the stem on the body to send vibration into tissue and bone."
  },
  {
    "id": "lumi-singing-bowls",
    "category": "bowls",
    "categoryName": "Singing Bowls",
    "label": "Lumi",
    "name": "Lumi Singing Bowls",
    "meta": "Brass · Rainbow Finish",
    "desc": "Lightweight, resonant bowls, hand-hammered from brass and fired to a shimmering rainbow sheen. Each carries a unique frequency — clear highs in the small bowls, deep lows in the large.",
    "priceClass": "udara-card__price",
    "price": "1.750.000 <small>IDR · per kilo</small>",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/lumi.jpg",
    "webp": "assets/products/lumi.webp",
    "alt": "Lumi",
    "howto": "Strike the rim softly for a single bloom of sound, or circle it slowly with the mallet to build a continuous, enveloping tone."
  },
  {
    "id": "dolphin-sounds",
    "category": "bowls",
    "categoryName": "Singing Bowls",
    "label": "Dolphin Sounds",
    "name": "Dolphin Sounds",
    "meta": "Water Bowl",
    "desc": "Add a little water and run the mallet around the rim: the vibration sets standing waves dancing on the surface — rippling, spraying, drawing the resonance into visible form.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/lumi.jpg",
    "webp": "assets/products/lumi.webp",
    "alt": "Dolphin Sounds",
    "howto": "Strike the rim softly for a single bloom of sound, or circle it slowly with the mallet to build a continuous, enveloping tone."
  },
  {
    "id": "head-and-joint-bowl",
    "category": "bowls",
    "categoryName": "Singing Bowls",
    "label": "Head &amp; Joint",
    "name": "Head &amp; Joint Bowl",
    "meta": "Central Hole · Targeted",
    "desc": "A central hole channels the sound directly over joints, knuckles or the crown of the head — driving therapeutic frequencies deep into bone and tissue for focused, physical relief.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/lumi.jpg",
    "webp": "assets/products/lumi.webp",
    "alt": "Head &amp; Joint",
    "howto": "Strike the rim softly for a single bloom of sound, or circle it slowly with the mallet to build a continuous, enveloping tone."
  },
  {
    "id": "chakra-bowl-set",
    "category": "bowls",
    "categoryName": "Singing Bowls",
    "label": "Chakra Set",
    "name": "Chakra Bowl Set",
    "meta": "Set of 7 · Hand-Tuned",
    "desc": "Seven bowls tuned to the seven notes of the scale (C to B), each aligned to an energy centre. Played in sequence, a sonic massage that clears and realigns the body.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/lumi.jpg",
    "webp": "assets/products/lumi.webp",
    "alt": "Chakra Set",
    "howto": "Strike the rim softly for a single bloom of sound, or circle it slowly with the mallet to build a continuous, enveloping tone."
  },
  {
    "id": "mini-gift-box",
    "category": "bowls",
    "categoryName": "Singing Bowls",
    "label": "Mini Gift Box",
    "name": "Mini Gift Box",
    "meta": "Set of 7 · Miniature",
    "desc": "Seven small, finely-crafted bowls in an ascending scale — clear, pristine tones that clear stagnant energy and soothe the mind. The perfect companion for daily meditation, and an ideal gift.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/lumi.jpg",
    "webp": "assets/products/lumi.webp",
    "alt": "Mini Gift Box",
    "howto": "Strike the rim softly for a single bloom of sound, or circle it slowly with the mallet to build a continuous, enveloping tone."
  },
  {
    "id": "nepalese-singing-bowls",
    "category": "bowls",
    "categoryName": "Singing Bowls",
    "label": "Nepalese",
    "name": "Nepalese Singing Bowls",
    "meta": "Bronze · Full-Moon Forged",
    "desc": "From a small family workshop north of Kathmandu — handmade, hand-hammered bronze &ldquo;Purnima&rdquo; bowls, crafted under the full moon. Exceptional sound, ethical making, a 6–8 month wait worth every day.",
    "priceClass": "udara-card__price",
    "price": "2.400.000 <small>IDR · per kilo</small>",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "assets/products/lumi.jpg",
    "webp": "assets/products/lumi.webp",
    "alt": "Nepalese",
    "howto": "Strike the rim softly for a single bloom of sound, or circle it slowly with the mallet to build a continuous, enveloping tone."
  },
  {
    "id": "chau-gong",
    "category": "gongs",
    "categoryName": "Gongs & Mallets",
    "label": "Chau Gong",
    "name": "Chau Gong",
    "meta": "Hand-Forged · Bronze",
    "desc": "Hand-forged with a deep, earthy roar — the grounding voice of the collection. One soft strike releases a vast wave of overtones that washes through the body.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_GONGS]",
    "img": "",
    "webp": "",
    "alt": "Chau Gong",
    "howto": "Warm the gong with a few light touches, then strike the centre. Small mallet balls give bright highs, larger ones deep, rolling lows."
  },
  {
    "id": "wind-gong",
    "category": "gongs",
    "categoryName": "Gongs & Mallets",
    "label": "Wind Gong",
    "name": "Wind Gong",
    "meta": "Shimmering · Wide",
    "desc": "Blooms bright and wide, opening into a shimmering wash of overtones that fills a room and lifts the energy of a space.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_GONGS]",
    "img": "",
    "webp": "",
    "alt": "Wind Gong",
    "howto": "Warm the gong with a few light touches, then strike the centre. Small mallet balls give bright highs, larger ones deep, rolling lows."
  },
  {
    "id": "paiste-planetary",
    "category": "gongs",
    "categoryName": "Gongs & Mallets",
    "label": "Paiste Planetary",
    "name": "Paiste Planetary",
    "meta": "Cosmic Tuned · Paiste",
    "desc": "The world-renowned planetary gongs, each tuned to a specific cosmic frequency. Sizes and planetary tunings configured to your practice.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_GONGS]",
    "img": "",
    "webp": "",
    "alt": "Paiste Planetary",
    "howto": "Warm the gong with a few light touches, then strike the centre. Small mallet balls give bright highs, larger ones deep, rolling lows."
  },
  {
    "id": "gong-mallets-flumis",
    "category": "gongs",
    "categoryName": "Gongs & Mallets",
    "label": "Flumis",
    "name": "Gong Mallets · Flumis",
    "meta": "Mallets · 7 Sizes &amp; Colours",
    "desc": "Stroke the gong with the smaller balls for high, whale-song tones — the larger balls for deep, rumbling lows. One mallet, a whole range of voices.",
    "priceClass": "udara-card__price",
    "price": "160.000 <small>IDR · from</small>",
    "link": "[PAYMENT_LINK_GONGS]",
    "img": "",
    "webp": "",
    "alt": "Gong Mallets · Flumis",
    "howto": "Warm the gong with a few light touches, then strike the centre. Small mallet balls give bright highs, larger ones deep, rolling lows."
  },
  {
    "id": "zen-bell",
    "category": "chimes",
    "categoryName": "Chimes & Bells",
    "label": "Zen Bell",
    "name": "Zen Bell",
    "meta": "With Incense Holder",
    "desc": "A clear, sustained bell with an integrated incense holder — scent and sound together. As in the monasteries, it marks the start and end of meditation and calls the mind to the present.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Zen Bell",
    "howto": "Ring a bell to open and close your practice. Brush chimes by hand for a cascade — or hang the bamboo set and let the wind play it."
  },
  {
    "id": "swinging-chimes",
    "category": "chimes",
    "categoryName": "Chimes & Bells",
    "label": "Swinging Chimes",
    "name": "Swinging Chimes",
    "meta": "8 Tones · C Major (512 Hz)",
    "desc": "An 8-tone chakra sequence tuning all seven centres plus the Soul Star. Played together they cascade into a harmonic field that clears the body and restores its natural resonance.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Swinging Chimes",
    "howto": "Ring a bell to open and close your practice. Brush chimes by hand for a cascade — or hang the bamboo set and let the wind play it."
  },
  {
    "id": "bamboo-chimes",
    "category": "chimes",
    "categoryName": "Chimes & Bells",
    "label": "Bamboo Chimes",
    "name": "Bamboo Chimes",
    "meta": "Earth · Fire · Water · Air",
    "desc": "Tuned to the four elements. Play them by hand in meditation, or hang them to let the wind play — turning a passing breeze into a soft, spontaneous soundscape.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Bamboo Chimes",
    "howto": "Ring a bell to open and close your practice. Brush chimes by hand for a cascade — or hang the bamboo set and let the wind play it."
  },
  {
    "id": "shamanic-drum",
    "category": "drums",
    "categoryName": "Drums & Elemental",
    "label": "Shamanic Drum",
    "name": "Shamanic Drum",
    "meta": "Goatskin · Tunable",
    "desc": "Hand-crafted in Bali with natural goatskin for a deep, resonant, authentic voice. An integrated pump lets you precisely adjust the skin tension to suit humidity, temperature and feel.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Shamanic Drum",
    "howto": "Find a slow, steady pulse. The rhythm anchors your intention and shakes loose stagnant energy, easing you into a meditative state."
  },
  {
    "id": "thunder",
    "category": "drums",
    "categoryName": "Drums & Elemental",
    "label": "Thunder",
    "name": "Thunder",
    "meta": "Elemental",
    "desc": "A handcrafted instrument that reproduces the deep, rolling resonance of a storm — ideal for breaking up energetic stagnation and facilitating powerful emotional release.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Thunder",
    "howto": "Find a slow, steady pulse. The rhythm anchors your intention and shakes loose stagnant energy, easing you into a meditative state."
  },
  {
    "id": "rattles",
    "category": "drums",
    "categoryName": "Drums & Elemental",
    "label": "Rattles",
    "name": "Rattles",
    "meta": "Pangi Seeds · Kenari Nuts",
    "desc": "Handcrafted from natural, resonant seeds and nuts. Their continuous rhythm shakes loose energetic blockages, anchors intention and guides the practitioner into a meditative state.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Rattles",
    "howto": "Find a slow, steady pulse. The rhythm anchors your intention and shakes loose stagnant energy, easing you into a meditative state."
  },
  {
    "id": "small-harp",
    "category": "harps",
    "categoryName": "Harps",
    "label": "Small Harp",
    "name": "Small Harp",
    "meta": "16 Strings",
    "desc": "Compact and intimate — let your fingers fall gently across the strings for a cascading, angelic tone. Perfect for personal practice.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Small Harp",
    "howto": "Let your fingers fall gently across the strings. The cascading, angelic tones soothe the nervous system almost instantly."
  },
  {
    "id": "big-harp",
    "category": "harps",
    "categoryName": "Harps",
    "label": "Big Harp",
    "name": "Big Harp",
    "meta": "Standard · Monochord · Pentatonic",
    "desc": "A fuller, enveloping resonant field, available in standard, monochord and pentatonic tunings — configured to your practice.",
    "priceClass": "udara-card__price udara-card__price--ask",
    "price": "On request",
    "link": "[PAYMENT_LINK_BOUTIQUE]",
    "img": "",
    "webp": "",
    "alt": "Big Harp",
    "howto": "Let your fingers fall gently across the strings. The cascading, angelic tones soothe the nervous system almost instantly."
  }
];
